version: "3.7"
services:
  app:
    build: 
      context: ./.docker/nginx
    container_name: gao-webserver
    tty: true
    volumes:
      - .:/var/www/
      - .docker/logs/nginx:/var/log/nginx
    depends_on:
      - php
    labels: 
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:gao.localhost"
  php:
    build:
      args:
        user: cedrick
        uid: 1000
      context: ./.docker/php
    container_name: gao-php
    ports:
      - 9000:9000
    links:
      - db:mysqldb
    volumes:
      - .:/var/www
  node: 
    build:
      context: ./.docker/node
    container_name: gao-nodejs
    tty: true
    volumes: 
      - .:/home/node/app
  db:
    image: mysql:5.7
    container_name: gao-mydb
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9306:3306
    volumes:
      - .docker/volumes/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=gao-laravel-vuejs
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
  traefik: 
    image: traefik:1.7
    container_name: gao-laravel-traefik
    command: --docker --docker.exposedbydefault=false
    ports: 
      - "8001:80"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro